<?php

namespace App\Support;

use Illuminate\Support\Str;

class FilamentLabels
{
    /**
     * Map kolom DB / nama field ke label Bahasa Indonesia.
     */
    public const MAP = [
        'id' => 'ID',
        'code' => 'Kode',
        'name' => 'Nama',
        'name_en' => 'Nama (EN)',
        'full_name' => 'Nama Lengkap',
        'username' => 'Username',
        'email' => 'Email',
        'password' => 'Password',
        'avatar' => 'Foto Profil',
        'description' => 'Deskripsi',
        'notes' => 'Catatan',
        'address' => 'Alamat',
        'phone' => 'Telepon',
        'gender' => 'Jenis Kelamin',
        'religion' => 'Agama',
        'nationality' => 'Kewarganegaraan',
        'birth_place' => 'Tempat Lahir',
        'birth_date' => 'Tanggal Lahir',
        'is_active' => 'Aktif',
        'is_archived' => 'Diarsipkan',
        'is_open' => 'Dibuka',
        'is_locked' => 'Terkunci',
        'is_mandatory' => 'Wajib',
        'is_emergency' => 'Darurat',
        'is_lecturer' => 'Dosen',
        'is_dynamic' => 'Dinamis',
        'is_published' => 'Dipublikasi',
        'is_parallel' => 'Paralel',
        'is_taxable' => 'Kena Pajak',
        'is_recurring' => 'Berulang',
        'is_read' => 'Dibaca',
        'is_verified' => 'Terverifikasi',
        'is_final' => 'Final',
        'requires_signature' => 'Butuh Tanda Tangan',
        'requires_approval' => 'Butuh Approval',
        'can_reject' => 'Bisa Tolak',
        'mfa_enabled' => 'MFA Aktif',
        'mfa_secret' => 'MFA Secret',
        'last_login_at' => 'Login Terakhir',
        'last_login_ip' => 'IP Login Terakhir',
        'password_expires_at' => 'Password Kedaluwarsa',
        'failed_login_attempts' => 'Percobaan Login Gagal',
        'locked_until' => 'Terkunci Sampai',
        'email_verified_at' => 'Email Terverifikasi',
        'user_type' => 'Tipe User',
        'external_id' => 'NIM/NIDN/NIP',

        // Common timestamps
        'created_at' => 'Dibuat',
        'updated_at' => 'Diperbarui',
        'deleted_at' => 'Dihapus',
        'created_by' => 'Dibuat Oleh',
        'updated_by' => 'Diperbarui Oleh',
        'creator' => 'Dibuat Oleh',
        'updater' => 'Diperbarui Oleh',
        'approver' => 'Approver',
        'reviewer' => 'Reviewer',
        'submitter' => 'Pengirim',
        'delegate' => 'Delegasi',
        'role' => 'Role',
        'roles' => 'Role',
        'permission' => 'Permission', 
        'permissions' => 'Permission',
        'user' => 'Pengguna',
        'users' => 'Pengguna',
        'head' => 'Ketua',
        'dean' => 'Dekan',
        'advisor' => 'Dosen Wali',
        'requester' => 'Pengaju',
        'recipient' => 'Penerima',
        'waivedBy' => 'Dibebaskan Oleh',
        'lockedBy' => 'Dikunci Oleh',
        'submittedBy' => 'Diinput Oleh',
        'closedBy' => 'Ditutup Oleh',
        'substituteLecturer' => 'Dosen Pengganti',
        'approverUser' => 'User Approver',
        'currentStep' => 'Step Saat Ini',
        'defaultWorkflow' => 'Workflow Default',
        'classSession' => 'Sesi Kelas',
        'studyProgram' => 'Program Studi',
        'academicCalendar' => 'Kalender Akademik',
        'courseOffering' => 'Penawaran MK',
        'billingComponent' => 'Komponen Tagihan',
        'salaryComponent' => 'Komponen Gaji',
        'letterTemplate' => 'Template Surat',
        'letterRequest' => 'Pengajuan Surat',
        'thesisTopic' => 'Topik Skripsi',
        'mbkmProgram' => 'Program MBKM',
        'mbkmEnrollment' => 'Pendaftaran MBKM',
        'workflowStep' => 'Step Workflow',
        'payrollPeriod' => 'Periode Payroll',
        'gradeSchema' => 'Skema Nilai',
        'krsItem' => 'Item KRS',
        'enrollment' => 'KRS',
        'invoice' => 'Invoice',
        'payment' => 'Pembayaran',
        'scholarship' => 'Beasiswa',
        'student' => 'Mahasiswa',
        'lecturer' => 'Dosen',
        'employee' => 'Pegawai',
        'faculty' => 'Fakultas',
        'curriculum' => 'Kurikulum',
        'course' => 'Mata Kuliah',
        'classroom' => 'Ruangan',
        'grade' => 'Nilai',
        'announcement' => 'Pengumuman',
        'notification' => 'Notifikasi',
        'period' => 'Periode',
        'salary' => 'Gaji',
        'workflow' => 'Workflow',
        'step' => 'Step',
        'component' => 'Komponen',
        'template' => 'Template',
        'schedule' => 'Jadwal',
        'semester' => 'Semester',

        // Akademik
        'faculty_id' => 'Fakultas',
        'study_program_id' => 'Program Studi',
        'curriculum_id' => 'Kurikulum',
        'course_id' => 'Mata Kuliah',
        'prerequisite_course_id' => 'MK Prasyarat',
        'minimum_grade' => 'Nilai Minimum',
        'logic_operator' => 'Operator',
        'group_no' => 'Grup',
        'lecturer_id' => 'Dosen',
        'lecturer_ids' => 'Dosen',
        'student_id' => 'Mahasiswa',
        'classroom_id' => 'Ruang Kelas',
        'academic_calendar_id' => 'Kalender Akademik',
        'semester_id' => 'Semester',
        'course_offering_id' => 'Penawaran MK',
        'dean_id' => 'Dekan',
        'head_id' => 'Ketua',
        'academic_advisor_id' => 'Dosen Wali',
        'pddikti_code' => 'Kode PDDikti',
        'degree_level' => 'Jenjang',
        'accreditation' => 'Akreditasi',
        'accreditation_valid_until' => 'Akreditasi Berlaku Hingga',
        'version' => 'Versi',
        'effective_year' => 'Tahun Berlaku',
        'total_sks_required' => 'Total SKS Wajib',
        'sks_theory' => 'SKS Teori',
        'sks_practice' => 'SKS Praktik',
        'sks_field' => 'SKS Lapangan',
        'total_sks' => 'Total SKS',
        'semester' => 'Semester',
        'course_type' => 'Jenis MK',
        'learning_outcomes' => 'Capaian Pembelajaran',
        'nidn' => 'NIDN',
        'nidk' => 'NIDK',
        'nip' => 'NIP',
        'nik' => 'NIK',
        'functional_position' => 'Jabatan Fungsional',
        'structural_position' => 'Jabatan Struktural',
        'education_level' => 'Pendidikan',
        'expertise_keywords' => 'Bidang Keahlian',
        'employment_status' => 'Status Kepegawaian',
        'start_date' => 'Tanggal Mulai',
        'end_date' => 'Tanggal Selesai',
        'nim' => 'NIM',
        'enrollment_year' => 'Tahun Masuk',
        'status' => 'Status',
        'entry_path' => 'Jalur Masuk',
        'ukt_group' => 'Golongan UKT',
        'parent_name' => 'Nama Wali',
        'parent_phone' => 'Telepon Wali',
        'building' => 'Gedung',
        'floor' => 'Lantai',
        'capacity' => 'Kapasitas',
        'room_type' => 'Tipe Ruangan',
        'facilities' => 'Fasilitas',
        'academic_year' => 'Tahun Akademik',
        'krs_start' => 'Mulai KRS',
        'krs_end' => 'Akhir KRS',
        'lecture_start' => 'Mulai Kuliah',
        'lecture_end' => 'Akhir Kuliah',
        'uts_start' => 'Mulai UTS',
        'uts_end' => 'Akhir UTS',
        'uas_start' => 'Mulai UAS',
        'uas_end' => 'Akhir UAS',
        'grade_input_deadline' => 'Batas Input Nilai',
        'term' => 'Term',
        'letter' => 'Huruf',
        'min_score' => 'Nilai Minimum',
        'max_score' => 'Nilai Maksimum',
        'grade_point' => 'Bobot',
        'class_code' => 'Kelas',
        'quota' => 'Kuota',
        'enrolled_count' => 'Terdaftar',

        // Scheduling
        'schedule_id' => 'Jadwal',
        'class_session_id' => 'Sesi Kelas',
        'substitute_lecturer_id' => 'Dosen Pengganti',
        'meeting_count' => 'Jumlah Pertemuan',
        'meeting_number' => 'Pertemuan Ke',
        'session_date' => 'Tanggal Sesi',
        'start_time' => 'Jam Mulai',
        'end_time' => 'Jam Selesai',
        'topic' => 'Topik',
        'material_summary' => 'Ringkasan Materi',
        'day_of_week' => 'Hari',
        'check_method' => 'Metode Absensi',
        'check_in_at' => 'Waktu Absen',
        'teaching_sks' => 'SKS Mengajar',
        'advisory_sks' => 'SKS Pembimbing',
        'research_sks' => 'SKS Penelitian',
        'service_sks' => 'SKS Pengabdian',
        'additional_sks' => 'SKS Tambahan',
        'exam_type' => 'Jenis Ujian',
        'exam_date' => 'Tanggal Ujian',
        'proctor_ids' => 'Pengawas',

        // KRS
        'enrollment_id' => 'KRS',
        'max_sks' => 'SKS Maksimum',
        'total_sks_taken' => 'Total SKS Diambil',
        'approved_by' => 'Disetujui Oleh',
        'approved_at' => 'Tanggal Disetujui',
        'dropped_at' => 'Tanggal Drop',
        'krs_item_id' => 'Item KRS',
        'attendance_score' => 'Nilai Kehadiran',
        'assignment_score' => 'Nilai Tugas',
        'mid_score' => 'Nilai UTS',
        'final_score' => 'Nilai UAS',
        'extra_score' => 'Nilai Tambahan',
        'total_score' => 'Nilai Total',
        'letter_grade' => 'Huruf Mutu',
        'locked_at' => 'Dikunci Pada',
        'locked_by' => 'Dikunci Oleh',
        'submitted_by' => 'Diinput Oleh',
        'submitted_at' => 'Tanggal Input',
        'sks_attempted' => 'SKS Ditempuh',
        'sks_acquired' => 'SKS Lulus',
        'semester_gpa' => 'IPS',
        'cumulative_gpa' => 'IPK',
        'sks_cumulative' => 'SKS Kumulatif',
        'academic_status' => 'Status Akademik',
        'grade_id' => 'Nilai',
        'reason' => 'Alasan',
        'original_letter' => 'Huruf Asal',
        'revised_letter' => 'Huruf Revisi',
        'original_score' => 'Nilai Asal',
        'revised_score' => 'Nilai Revisi',
        'reviewed_by' => 'Direview Oleh',
        'reviewed_at' => 'Tanggal Review',
        'review_notes' => 'Catatan Review',

        // Finance
        'billing_component_id' => 'Komponen Tagihan',
        'invoice_id' => 'Invoice',
        'payment_id' => 'Pembayaran',
        'scholarship_id' => 'Beasiswa',
        'invoice_number' => 'Nomor Invoice',
        'payment_number' => 'Nomor Pembayaran',
        'refund_number' => 'Nomor Refund',
        'virtual_account' => 'Virtual Account',
        'bank_code' => 'Kode Bank',
        'bank_reference' => 'Referensi Bank',
        'bank_account' => 'Nomor Rekening',
        'bank_name' => 'Nama Bank',
        'issue_date' => 'Tanggal Terbit',
        'due_date' => 'Jatuh Tempo',
        'subtotal' => 'Subtotal',
        'discount_amount' => 'Diskon',
        'fine_amount' => 'Denda',
        'scholarship_amount' => 'Beasiswa',
        'total_amount' => 'Total',
        'paid_amount' => 'Sudah Dibayar',
        'amount' => 'Jumlah',
        'quantity' => 'Qty',
        'total' => 'Total',
        'installment_plan' => 'Skema Cicilan',
        'type' => 'Tipe',
        'payment_method' => 'Metode Bayar',
        'payment_date' => 'Tanggal Bayar',
        'reconciled_at' => 'Direkonsiliasi',
        'raw_payload' => 'Payload',
        'covered_components' => 'Komponen Ditanggung',
        'coverage_type' => 'Tipe Coverage',
        'coverage_value' => 'Nilai Coverage',
        'granted_amount' => 'Jumlah Diberikan',
        'waived' => 'Dibebaskan',
        'waived_by' => 'Dibebaskan Oleh',
        'waived_at' => 'Tanggal Pembebasan',
        'waive_reason' => 'Alasan Pembebasan',
        'disbursed_at' => 'Tanggal Pencairan',

        // E-Office
        'letter_template_id' => 'Template Surat',
        'workflow_id' => 'Workflow',
        'workflow_step_id' => 'Step Workflow',
        'letter_request_id' => 'Pengajuan Surat',
        'current_step_id' => 'Step Saat Ini',
        'default_workflow_id' => 'Workflow Default',
        'requester_id' => 'Pengaju',
        'approver_id' => 'Approver',
        'approver_role_id' => 'Role Approver',
        'approver_user_id' => 'User Approver',
        'delegated_to' => 'Didelegasi Ke',
        'letter_number' => 'Nomor Surat',
        'body' => 'Isi',
        'subject' => 'Subjek',
        'category' => 'Kategori',
        'numbering_pattern' => 'Pola Nomor',
        'entity_type' => 'Tipe Entitas',
        'step_order' => 'Urutan',
        'sla_hours' => 'SLA (Jam)',
        'form_data' => 'Data Form',
        'pdf_url' => 'PDF',
        'qr_code' => 'QR Code',
        'qr_valid_until' => 'QR Berlaku Hingga',
        'issued_at' => 'Diterbitkan',
        'action' => 'Aksi',
        'comments' => 'Komentar',
        'acted_at' => 'Waktu Aksi',
        'provider' => 'Provider',
        'certificate_data' => 'Data Sertifikat',
        'certificate_serial' => 'Serial Sertifikat',
        'valid_from' => 'Berlaku Dari',
        'valid_until' => 'Berlaku Hingga',
        'searchable_text' => 'Teks Cari',
        'metadata' => 'Metadata',
        'archived_at' => 'Diarsipkan Pada',

        // Thesis
        'thesis_topic_id' => 'Topik Skripsi',
        'mbkm_program_id' => 'Program MBKM',
        'mbkm_enrollment_id' => 'Pendaftaran MBKM',
        'advisor_order' => 'Urutan Pembimbing',
        'assigned_at' => 'Ditugaskan',
        'title' => 'Judul',
        'title_en' => 'Judul (EN)',
        'abstract' => 'Abstrak',
        'keywords' => 'Kata Kunci',
        'research_field' => 'Bidang Penelitian',
        'similarity_score' => 'Skor Kemiripan',
        'plagiarism_score' => 'Skor Plagiarisme',
        'duration_minutes' => 'Durasi (Menit)',
        'topic_discussed' => 'Topik Dibahas',
        'progress_summary' => 'Ringkasan Progres',
        'lecturer_feedback' => 'Feedback Dosen',
        'verified_at' => 'Diverifikasi',
        'defense_type' => 'Jenis Sidang',
        'scheduled_at' => 'Dijadwalkan',
        'room' => 'Ruangan',
        'examiner_ids' => 'Penguji',
        'partner_name' => 'Nama Mitra',
        'partner_address' => 'Alamat Mitra',
        'sks_converted' => 'SKS Konversi',
        'report_url' => 'Laporan',
        'publish_year' => 'Tahun Terbit',
        'doi' => 'DOI',
        'file_url' => 'File',
        'review_status' => 'Status Review',

        // Communication
        'recipient_id' => 'Penerima',
        'announcement_id' => 'Pengumuman',
        'erp_notification_id' => 'Notifikasi',
        'template_code' => 'Kode Template',
        'event' => 'Event',
        'channels' => 'Channel',
        'channel' => 'Channel',
        'body_email' => 'Body Email',
        'body_wa' => 'Body WA',
        'body_push' => 'Body Push',
        'body_inapp' => 'Body In-App',
        'variables' => 'Variabel',
        'audience_filter' => 'Filter Audiens',
        'sent_at' => 'Dikirim',
        'recipient_count' => 'Jumlah Penerima',
        'payload' => 'Payload',
        'read_at' => 'Dibaca Pada',
        'filter_rules' => 'Aturan Filter',
        'last_count' => 'Jumlah Terakhir',
        'last_resolved_at' => 'Diresolusi Terakhir',
        'provider_message_id' => 'ID Pesan Provider',
        'error_message' => 'Pesan Error',
        'attempts' => 'Percobaan',
        'delivered_at' => 'Diterima',

        // HRIS
        'employee_id' => 'Pegawai',
        'payroll_period_id' => 'Periode Payroll',
        'salary_id' => 'Gaji',
        'salary_component_id' => 'Komponen Gaji',
        'unit_id' => 'Unit',
        'employee_type' => 'Tipe Pegawai',
        'rank_grade' => 'Golongan',
        'base_salary' => 'Gaji Pokok',
        'npwp' => 'NPWP',
        'bpjs_kesehatan' => 'BPJS Kesehatan',
        'bpjs_ketenagakerjaan' => 'BPJS Ketenagakerjaan',
        'event_type' => 'Jenis Event',
        'effective_date' => 'Tanggal Berlaku',
        'from_value' => 'Nilai Lama',
        'to_value' => 'Nilai Baru',
        'work_date' => 'Tanggal Kerja',
        'check_out_at' => 'Jam Pulang',
        'check_in_method' => 'Metode Masuk',
        'check_out_method' => 'Metode Pulang',
        'check_in_location' => 'Lokasi Masuk',
        'check_out_location' => 'Lokasi Pulang',
        'late_minutes' => 'Terlambat (Menit)',
        'early_leave_minutes' => 'Pulang Cepat (Menit)',
        'leave_type' => 'Jenis Cuti',
        'total_days' => 'Total Hari',
        'attachment_url' => 'Lampiran',
        'rejection_reason' => 'Alasan Ditolak',
        'month' => 'Bulan',
        'year' => 'Tahun',
        'period_start' => 'Mulai Periode',
        'period_end' => 'Akhir Periode',
        'cutoff_date' => 'Tanggal Cutoff',
        'closed_at' => 'Ditutup',
        'closed_by' => 'Ditutup Oleh',
        'calculation_type' => 'Tipe Kalkulasi',
        'formula' => 'Formula',
        'total_allowance' => 'Total Tunjangan',
        'teaching_honor' => 'Honor Mengajar',
        'other_income' => 'Pendapatan Lain',
        'gross_total' => 'Total Bruto',
        'bpjs_deduction' => 'Potongan BPJS',
        'tax_pph21' => 'PPh 21',
        'other_deduction' => 'Potongan Lain',
        'total_deduction' => 'Total Potongan',
        'net_total' => 'Total Netto',
        'paid_at' => 'Dibayar Pada',
        'slip_pdf_url' => 'Slip PDF',
        'rate_per_sks' => 'Rate per SKS',
        'sks' => 'SKS',
        'tax_year' => 'Tahun Pajak',
        'gross_year_to_date' => 'Bruto YTD',
        'ptkp_category' => 'Kategori PTKP',
        'ptkp_amount' => 'Jumlah PTKP',
        'taxable_income' => 'Penghasilan Kena Pajak',
        'tax_pph21_ytd' => 'PPh 21 YTD',
    ];

    public static function translate(string $name): string
    {
        if (isset(self::MAP[$name])) {
            return self::MAP[$name];
        }

        // Dot notation: relation.column → translate the relation part.
        // e.g. faculty.name → "Fakultas", studyProgram.name → "Program Studi".
        if (str_contains($name, '.')) {
            $relation = Str::before($name, '.');
            $snake = Str::snake($relation);

            if (isset(self::MAP[$snake])) {
                return self::MAP[$snake];
            }
            if (isset(self::MAP[$snake.'_id'])) {
                return self::MAP[$snake.'_id'];
            }

            // Plural relationship (e.g. roles.name → "Roles")
            $singular = Str::singular($snake);
            if (isset(self::MAP[$singular])) {
                return self::MAP[$singular];
            }
            if (isset(self::MAP[$singular.'_id'])) {
                return self::MAP[$singular.'_id'];
            }

            return Str::headline($relation);
        }

        // Common suffix stripping (_id → bare name)
        $stripped = preg_replace('/_id$/', '', $name);
        if ($stripped && isset(self::MAP[$stripped])) {
            return self::MAP[$stripped];
        }

        return Str::headline($name);
    }
}
